services:

  postgres:
    ports: !reset []

  redis:
    ports: !reset []

  minio:
    ports: !reset []

  api:
    ports: !reset []
    environment:
      CORS_ORIGINS: '["https://docai.az"]'
      FRONTEND_BASE_URL: https://docai.az
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.dms-api.rule=Host(`api.docai.az`)
      - traefik.http.routers.dms-api.entrypoints=web
      - traefik.http.services.dms-api.loadbalancer.server.port=8000

  worker:
    networks:
      - default

  frontend:
    build:
      args:
        NEXT_PUBLIC_API_URL: https://api.docai.az
    environment:
      NEXT_PUBLIC_API_URL: https://api.docai.az
      HOSTNAME: 0.0.0.0
    ports: !reset []
    networks:
      - default
      - proxy
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.dms.rule=Host(`docai.az`)
      - traefik.http.routers.dms.entrypoints=web
      - traefik.http.services.dms.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
